spring:
  datasource:
    url:  jdbc:mysql://45.33.14.177/assessment3
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: dev
    password: devpass


server:
  servlet:
    context-path: /assessment3